Update Screenshots
ArasLabs/visual-user-listing pull request #5
Opened 2019-08-02 20:48 UTC by sampoearas

- Updated screenshots to v12

2019-08-02 21:13 UTC, EliJDonahue requested changes
Just a note in addition to the requested changes - there's no reason you *have to* change image names when you update them.

2019-08-02 21:13 UTC, EliJDonahue commented on README.md
> +[v1.0.2](https://github.com/ArasLabs/visual-user-listing/releases/tag/v1.0.2) | 11.9+, 12.0+
```suggestion
[v1.0.2](https://github.com/ArasLabs/visual-user-listing/releases/tag/v1.0.2) | 11.0 SP9+, 12.0+ 
```

2019-08-02 21:13 UTC, EliJDonahue commented on README.md
> +1. Aras Innovator installed (version 12.0 preferred)
```suggestion
1. Aras Innovator installed (see "Supported Aras Versions" above)
```

2019-08-05 13:12 UTC, sampoearas commented
Suggestions accepted.

2019-08-06 23:16 UTC, EliJDonahue approved these changes

2019-08-07 12:56 UTC, merged